# Install Ansible Roles
# ---------------------
# When the build process starts `ansible-galaxy install -r requirements.yml` is executed
# using this file. Follow the instructions at http://docs.ansible.com/ansible/galaxy.html
# to include any roles you want intalled prior to running main.yml.

- src: geerlingguy.solr
  path: external_roles/

- src: geerlingguy.java
  path: external_roles/

- src: geerlingguy.repo-epel
  path: external_roles/

- src: zzet.rbenv
  path: external_roles/
  version: 2.2.5
